NUM_FEATURES = [
        "GOLD_DENSITY",
        "SILVER_DENSITY",
        "PRECIOUS_ORE_DENSITY",
        "COPPER_GRADE",
        "INITIAL_COST",
        "ORE_TONNAGE",
        "PRECIOUS_TONNAGE",
        "COPPER_TONNAGE",
        "ECONOMIC_TONNAGE",
        "GOLD_TONNAGE",
        "SILVER_TONNAGE",
        'INITIAL_COST_PER_TONNE',
        "LOG_10_GOLD_DENSITY",
        "LOG_10_SILVER_DENSITY",
        "LOG_10_PRECIOUS_ORE_DENSITY",
        "LOG_10_COPPER_GRADE",
        "LOG_10_INITIAL_COST",
        "LOG_10_ORE_TONNAGE",
        "LOG_10_PRECIOUS_TONNAGE",
        "LOG_10_COPPER_TONNAGE",
        "LOG_10_ECONOMIC_TONNAGE",
        "LOG_10_GOLD_TONNAGE",
        "LOG_10_SILVER_TONNAGE",
        'LOG_10_INITIAL_COST_PER_TONNE'
        #Capacidade de processamento
        #"PRICE_PER_TONNE_MAIN_ORE",
    ]

CAT_FEATURES = [
    "GEOLOGIC_ORE_BODY_TYPE",
    "GLOBAL_REGION",
    "MINE_TYPE"
]

FEATURES = NUM_FEATURES + CAT_FEATURES

NUM_SELECTED = [
    'COPPER_GRADE', 'GOLD_DENSITY',
    'LOG_10_COPPER_GRADE', 'INITIAL_COST_PER_TONNE', 
    'INITIAL_COST', 'LOG_10_GOLD_DENSITY', 
    'LOG_10_INITIAL_COST', 'LOG_10_INITIAL_COST_PER_TONNE'
]

CAT_SELECTED = ['GLOBAL_REGION']

SELECTED_FEATURES = NUM_SELECTED + CAT_SELECTED

N_COMP = 4