NUM_FEATURES = [
        "GOLD_DENSITY",
        "SILVER_DENSITY",
        "PRECIOUS_ORE_DENSITY",
        "COPPER_GRADE",
        "INITIAL_COST",
        "ORE_TONNAGE",
        "PRECIOUS_TONNAGE",
        "COPPER_TONNAGE",
        "ECONOMIC_TONNAGE",
        "GOLD_TONNAGE",
        "SILVER_TONNAGE",
        'INITIAL_COST_PER_TONNE',
        "LOG_10_GOLD_DENSITY",
        "LOG_10_SILVER_DENSITY",
        "LOG_10_PRECIOUS_ORE_DENSITY",
        "LOG_10_COPPER_GRADE",
        "LOG_10_INITIAL_COST",
        "LOG_10_ORE_TONNAGE",
        "LOG_10_PRECIOUS_TONNAGE",
        "LOG_10_COPPER_TONNAGE",
        "LOG_10_ECONOMIC_TONNAGE",
        "LOG_10_GOLD_TONNAGE",
        "LOG_10_SILVER_TONNAGE",
        'LOG_10_INITIAL_COST_PER_TONNE'
        #Capacidade de processamento
        #"PRICE_PER_TONNE_MAIN_ORE",
    ]

CAT_FEATURES = [
    "GEOLOGIC_ORE_BODY_TYPE",
    "GLOBAL_REGION",
    "MINE_TYPE"
]

FEATURES = NUM_FEATURES + CAT_FEATURES

#NUM_SELECTED = ['GOLD_DENSITY',
# 'SILVER_DENSITY',
# 'PRECIOUS_ORE_DENSITY',
# 'COPPER_GRADE',
# 'INITIAL_COST',
# 'ORE_TONNAGE',
# 'COPPER_TONNAGE',
# 'GOLD_TONNAGE',
# 'LOG_10_PRECIOUS_ORE_DENSITY',
# 'INITIAL_COST_PER_TONNE',
# 'LOG_10_SILVER_DENSITY',
# 'LOG_10_GOLD_DENSITY',
# 'LOG_10_COPPER_GRADE',
# 'LOG_10_COPPER_TONNAGE',
# 'LOG_10_ORE_TONNAGE',
# 'LOG_10_INITIAL_COST',
# 'LOG_10_INITIAL_COST_PER_TONNE']

#CAT_SELECTED = ['GLOBAL_REGION_2', 'MINE_TYPE_1', 'GLOBAL_REGION_0']

NUM_SELECTED = ['COPPER_GRADE', 'GOLD_DENSITY',
       'LOG_10_COPPER_GRADE', 'INITIAL_COST_PER_TONNE', 'INITIAL_COST',
       'LOG_10_GOLD_DENSITY', 'LOG_10_INITIAL_COST',
       'LOG_10_INITIAL_COST_PER_TONNE']

CAT_SELECTED = ['GLOBAL_REGION_2', 'GLOBAL_REGION_0']

SELECTED_FEATURES = NUM_SELECTED + CAT_SELECTED


RANDOM_FOREST_PARAMS = {
    "n_estimators":6,
    "max_depth":5,
    "max_features":1,
    "min_samples_split":50,
    "min_samples_leaf":4,
    "random_state":17,
    "n_jobs":-1,
    "class_weight":'balanced'
}