NUM_FEATURES = [
        "GOLD_DENSITY",
        "SILVER_DENSITY",
        "PRECIOUS_ORE_DENSITY",
        "COPPER_GRADE",
        "INITIAL_COST",
        "ORE_TONNAGE",
        "PRECIOUS_GRAMS",
        "COPPER_TONNAGE",
        "ECONOMIC_AMOUNT",
        "GOLD_GRAMS",
        "SILVER_GRAMS",
        'INITIAL_COST_PER_AMOUNT',
        "LOG_10_GOLD_DENSITY",
        "LOG_10_SILVER_DENSITY",
        "LOG_10_PRECIOUS_ORE_DENSITY",
        "LOG_10_COPPER_GRADE",
        "LOG_10_INITIAL_COST",
        "LOG_10_ORE_TONNAGE",
        "LOG_10_PRECIOUS_GRAMS",
        "LOG_10_COPPER_TONNAGE",
        "LOG_10_ECONOMIC_AMOUNT",
        "LOG_10_GOLD_GRAMS",
        "LOG_10_SILVER_GRAMS",
        'LOG_10_INITIAL_COST_PER_AMOUNT'
    ]

CAT_FEATURES = [
    "GEOLOGIC_ORE_BODY_TYPE",
    "GLOBAL_REGION",
    "MINE_TYPE"
]

FEATURES = NUM_FEATURES + CAT_FEATURES

NUM_SELECTED = ['INITIAL_COST_PER_AMOUNT', 'INITIAL_COST', 'LOG_10_COPPER_TONNAGE',
       'COPPER_GRADE', 'GOLD_GRAMS', 'LOG_10_INITIAL_COST',
       'LOG_10_GOLD_DENSITY', 'ORE_TONNAGE', 'GOLD_DENSITY',
       'LOG_10_COPPER_GRADE', 'SILVER_GRAMS']

CAT_SELECTED = ['GLOBAL_REGION']

SELECTED_FEATURES = NUM_SELECTED + CAT_SELECTED